package estat

// Code generated by github.com/psyark/estat/codegen; DO NOT EDIT.

// TableInfHelper は、TableInf の単一の値または配列を透過的にUnmarshal/Marshalするスライスです
type TableInfHelper []TableInf

func (c *TableInfHelper) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]TableInf)(c), d)
}

func (c TableInfHelper) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}
