package estat

import "encoding/json"

// Code generated by github.com/psyark/estat/codegen; DO NOT EDIT.

// TableInfHelper は、TableInf の単一の値または配列を透過的にUnmarshal/Marshalするスライスです
type TableInfHelper []TableInf

func (c *TableInfHelper) UnmarshalJSON(d []byte) error {
	if d[0] == '{' {
		*c = make([]TableInf, 1)
		return json.Unmarshal(d, &(*c)[0])
	} else {
		return json.Unmarshal(d, (*[]TableInf)(c))
	}
}

func (c TableInfHelper) MarshalJSON() ([]byte, error) {
	if len(c) == 1 {
		return json.Marshal(c[0])
	} else {
		return json.Marshal([]TableInf(c))
	}
}
