package estat

// Code generated by github.com/psyark/estat/codegen; DO NOT EDIT.

// ClassHelper は、Class の単一の値または配列を透過的にUnmarshal/Marshalするスライスです
type ClassHelper []Class

func (c *ClassHelper) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]Class)(c), d)
}

func (c ClassHelper) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}

// NoteHelper は、Note の単一の値または配列を透過的にUnmarshal/Marshalするスライスです
type NoteHelper []Note

func (c *NoteHelper) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]Note)(c), d)
}

func (c NoteHelper) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}

// ValueHelper は、Value の単一の値または配列を透過的にUnmarshal/Marshalするスライスです
type ValueHelper []Value

func (c *ValueHelper) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]Value)(c), d)
}

func (c ValueHelper) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}

// TableInfHelper は、TableInf の単一の値または配列を透過的にUnmarshal/Marshalするスライスです
type TableInfHelper []TableInf

func (c *TableInfHelper) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]TableInf)(c), d)
}

func (c TableInfHelper) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}
