package estat

// Code generated by github.com/psyark/estat/codegen; DO NOT EDIT.

// ClassList は、Class または []Class を透過的にUnmarshalし、元通りにMarshalするスライスです
type ClassList []Class

func (c *ClassList) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]Class)(c), d)
}

func (c ClassList) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}

// NoteList は、Note または []Note を透過的にUnmarshalし、元通りにMarshalするスライスです
type NoteList []Note

func (c *NoteList) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]Note)(c), d)
}

func (c NoteList) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}

// ValueList は、Value または []Value を透過的にUnmarshalし、元通りにMarshalするスライスです
type ValueList []Value

func (c *ValueList) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]Value)(c), d)
}

func (c ValueList) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}

// TableInfList は、TableInf または []TableInf を透過的にUnmarshalし、元通りにMarshalするスライスです
type TableInfList []TableInf

func (c *TableInfList) UnmarshalJSON(d []byte) error {
	return unmarshalList((*[]TableInf)(c), d)
}

func (c TableInfList) MarshalJSON() ([]byte, error) {
	return marshalList(c)
}
